# This is a basic workflow to help you get started with Actions

name: Deployment React Blog CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash
    working-directory: ./app

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  KUBECTL_CONFIG: ${{ secrets.KUBECTL_CONFIG }}
  # TODO: 下面的设置目录有多次使用, 如果要更改不方便, 所以尽量提取成一个变量引用

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: ${{ secrets.DOCKER_USERNAME }}/front-blog
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # 2022-11-14: 不知为何, 不指定 tags 时, 不会以 latest 为默认值发布了, 会以一个随机的哈希值为默认
          #             所以手动指定为 latest, 方便 ci/cd k8s 拉取镜像, 自动拉取 tag 为 latest 的镜像
          tags: "latest"
        
      # - name: Publish to Registry
      #   uses: elgohr/Publish-Docker-Github-Action@v4
      #   with:
      #     name: front-blog
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     # 2022-11-14: 不知为何, 不指定 tags 时, 不会以 latest 为默认值发布了, 会以一个随机的哈希值为默认
      #     #             所以手动指定为 latest, 方便 ci/cd k8s 拉取镜像, 自动拉取 tag 为 latest 的镜像
      #     tags: "latest"
      #     registry: registry.cn-zhangjiakou.aliyuncs.com/zhujianxintian
      #               registry-1.docker.io/v2/
      
      - name: Setup config
        run: |
          mkdir ~/.kube
          echo "${KUBECTL_CONFIG}" > ~/.kube/config

      - name: Install kubectl
        uses: possie-engine/gha-tools/kubectl@latest
      
      - name: Rollout the k8s deployment
        run: kubectl rollout restart deployment -n front blog-deployment